<a href="https://colab.research.google.com/github/Sushanth-arava/Deep_Learning/blob/master/Pytorch_1(Tensors).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("lol")

Tesla T4


In [ ]:
import numpy as np

In [ ]:
b=torch.empty(2,3) #this function create a tensor and  allocates memory and these values are default values already exsiting there
print(b)

tensor([[0.3997, 0.0000, 0.4143],
        [0.0000, 0.2275, 0.0000]])


In [ ]:
type(b)

torch.Tensor

In [ ]:
z=torch.zeros(3,4)
print(z)
z1=torch.ones(3,4)
print(z1)
z2=torch.rand(3,4)
print(z2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.8547, 0.0659, 0.7880, 0.5462],
        [0.7150, 0.7366, 0.0790, 0.7091],
        [0.3339, 0.1496, 0.9318, 0.2220]])


In [ ]:
#when we want to use rand but the value should be same everytime we run it
torch.manual_seed(100)
z3=torch.rand(3,4)
print(z3)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])


In [ ]:
torch.manual_seed(100) # we use manual_seed to make use the same random values appear every time we run the code
z3=torch.rand(3,4)
print(z3)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])


In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print("arange",torch.arange(0,10,2)) #range= 0-10 and step 2
print("linspace",torch.linspace(0,10,5)) #linearly space range=0-10 5 evenly spaced values
print("eye",torch.eye(5)) #identity matrix
print("full",torch.full((2,3),5))

arange tensor([0, 2, 4, 6, 8])
linspace tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full tensor([[5, 5, 5],
        [5, 5, 5]])


In [ ]:
x= torch.tensor([[1,2,3],[4,5,6]])
x.size()

torch.Size([2, 3])

In [ ]:
b=torch.empty_like(x) # will give same shape as x

In [ ]:
print(b)

tensor([[   136410640911744,         1061372544,          359268476],
        [                 0,  48132221017522176, 755478837491400704]])


In [ ]:
c=torch.zeros_like(x)
print(c)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [ ]:
#Tensor Datatypes

x1=torch.tensor([1.0,2.0,3.0],dtype=torch.int32) #to store float type into int
x1.dtype
x2=torch.tensor([1,2,3],dtype=torch.float)
x2.dtype

torch.float32

In [ ]:
x.dtype

torch.int64

In [ ]:
x.to(dtype=torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])

In [ ]:
x=torch.rand(2,2)
print(x)

tensor([[0.1629, 0.8902],
        [0.5163, 0.0359]])


In [ ]:
x+2

tensor([[2.1629, 2.8902],
        [2.5163, 2.0359]])

In [ ]:
x**2

tensor([[0.0265, 0.7925],
        [0.2665, 0.0013]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])
tensor([[0.9051, 0.5989, 0.4450],
        [0.7278, 0.4563, 0.3389]])


In [ ]:

a - b



tensor([[-0.2574, -0.2558, -0.1268],
        [-0.2017, -0.4116,  0.1735]])

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 7., 8.],
        [3., 6., 1.]])

In [ ]:
torch.sum(e, dim=0)

tensor([10., 13.,  9.])

In [ ]:
torch.sum(e, dim=1)

tensor([22., 10.])

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 5, 0],
        [4, 3, 8]])
tensor([[8, 3],
        [3, 5],
        [0, 6]])


In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)