<a href="https://colab.research.google.com/github/Sushanth-arava/Deep_Learning/blob/master/Pytorch_3_codeflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

### StandardScalar:
##### Standardizes numerical features It transforms the data so that:

The mean = 0

The standard deviation = 1

Formula applied for each value:

z=(x-μ​)/σ
where

x = original value,

μ = mean of the feature,

σ = standard deviation of the feature.

#### LabelEncoder
from sklearn.preprocessing import LabelEncoder


Purpose: Converts categorical labels (strings) into numeric form.

Each unique class is mapped to an integer (0, 1, 2, …).

🔹 Why we use it?

ML models work with numbers, not text.

Example: A column like ["Male", "Female", "Female", "Male"] → [1, 0, 0, 1].

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

### Remove uncesssary columns like id and unnamed 32

In [6]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)
# axis=1

# Tells pandas what to drop:

# axis=0 → drop rows (by index).

# axis=1 → drop columns (by name).

# Since we’re removing columns, it must be axis=1.

# 3. inplace=True

# By default, drop() returns a new DataFrame.

# With inplace=True, it modifies df directly without creating a copy.

# So after this line, df no longer has the id or Unnamed: 32 column

In [7]:
df


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

### Split the datset for testing and training

In [8]:
X_train,X_test,y_train,y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

### Scale the dataset

In [12]:
scalar= StandardScaler()
scalar.fit(X_train)
X_train_scaled=scalar.transform(X_train)
X_test_scaled=scalar.transform(X_test)

In [14]:
X_train_scaled

array([[-0.66434745, -0.48771453, -0.6940142 , ..., -0.97831684,
        -0.24747514, -0.18850897],
       [-0.12095813,  0.3677028 , -0.07756631, ...,  0.59196628,
         0.40918797,  1.6415771 ],
       [ 0.87193649,  1.25187366,  0.91271141, ...,  1.11980547,
         0.59343157,  2.65679157],
       ...,
       [-1.16221725, -0.4230191 , -1.14170226, ..., -0.80242174,
        -0.066381  , -0.43529249],
       [ 0.23181818, -0.12589936,  0.2376721 , ..., -0.50910935,
        -0.13251973,  0.40387947],
       [ 0.44519095,  0.2431042 ,  0.37631098, ...,  0.56888294,
         0.7886983 ,  0.08689495]])

In [15]:
y_train

399    B
7      M
72     M
212    M
368    M
      ..
512    M
162    M
338    B
147    B
182    M
Name: diagnosis, Length: 455, dtype: object

#### Encode the y_train and y_test using label encoder


In [16]:
encoded=LabelEncoder()
y_train=encoded.fit_transform(y_train)
y_test=encoded.fit_transform(y_test)

In [18]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,

In [17]:
y_test

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0])

In [19]:
X_train_tensor=torch.from_numpy(X_train_scaled)
X_test_tensor=torch.from_numpy(X_test_scaled)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [20]:
y_train_tensor.shape

torch.Size([455])

## Lets define NN

##### For now we are using only one neuron to take in all the inputs

In [47]:
class simpleNeuralNetwork():

  def __init__(self,X):

    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True) # create a matrix for weights with the shape of first row of X and set them as 1
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True) #since one neuron,one bias only

  def forward(self,X):
    return torch.sigmoid(torch.matmul(X,self.weights)+self.bias)

  def calculate_loss(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss






In [21]:
#Important parameters

learning_rate=0.1
epochs=25

### Create Model

In [50]:
model=simpleNeuralNetwork(X_train_tensor)
model.weights

#define loop
for epoch in range(epochs):
  #forward pass: wx+b=z and sigmoid(z)
  y_pred=model.forward(X_train_tensor)


  #calculate loss

  loss=model.calculate_loss(y_pred,y_train_tensor)


  #calculate gradients
  loss.backward()

  #update weights
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()


  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')





Epoch: 1, Loss: 3.3404294194228643
Epoch: 2, Loss: 3.196305555186001
Epoch: 3, Loss: 3.047155360072642
Epoch: 4, Loss: 2.89530421855205
Epoch: 5, Loss: 2.742043051431645
Epoch: 6, Loss: 2.586042823228125
Epoch: 7, Loss: 2.427418342210178
Epoch: 8, Loss: 2.265325340525679
Epoch: 9, Loss: 2.1027354992125593
Epoch: 10, Loss: 1.9455073350307037
Epoch: 11, Loss: 1.7877320203427858
Epoch: 12, Loss: 1.6373037712520253
Epoch: 13, Loss: 1.4925225450072583
Epoch: 14, Loss: 1.3547723379831649
Epoch: 15, Loss: 1.2292268493907883
Epoch: 16, Loss: 1.1207290441983158
Epoch: 17, Loss: 1.03033618715065
Epoch: 18, Loss: 0.9580395401826531
Epoch: 19, Loss: 0.9025207930127553
Epoch: 20, Loss: 0.8613183542449604
Epoch: 21, Loss: 0.8313843622113001
Epoch: 22, Loss: 0.8097137808488943
Epoch: 23, Loss: 0.7937708770578389
Epoch: 24, Loss: 0.7816512012803526
Epoch: 25, Loss: 0.7720461883559637


In [51]:
model.weights

tensor([[-0.2636],
        [ 0.1381],
        [ 0.0835],
        [ 0.3894],
        [ 0.0269],
        [-0.5018],
        [ 0.3019],
        [ 0.0687],
        [ 0.2307],
        [ 0.0248],
        [ 0.2703],
        [ 0.0040],
        [-0.1918],
        [-0.2121],
        [ 0.5451],
        [-0.2559],
        [ 0.5817],
        [ 0.2618],
        [ 0.1142],
        [-0.2912],
        [ 0.3153],
        [ 0.0228],
        [-0.1633],
        [ 0.1952],
        [-0.0373],
        [ 0.1490],
        [-0.2059],
        [-0.4964],
        [-0.2156],
        [ 0.1771]], dtype=torch.float64, requires_grad=True)

### model evaluation

In [54]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  print(y_pred)
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
      